apiVersion: v1
kind: service
metadata:
  name: nginx
spec:
  type: {{ .Values.service.type }}
  selector:
    project: roboshop
    environment: dev
    tier: db
    component: mongodb

  ports:
  - protocol: TCP
    port: 27017
    targetPort: 27017